### PR TITLE
Created a description of why user stories are effective

### PR DESCRIPTION
**Pull request by kirill2222**

### CODE REVIEW

**Comment by kirill2222** [comment]
michelle said she didn't see this one so i closed it but if it looks good lets leave it. Sorry for the confusion.

**Comment by tsye15** [comment]
@michelleeeee does @kirill2222  PR look okay? if so let's go ahead and merge it.

**Comment by tsye15** [comment]
Ok. I'm going to merge. Wendy @wenders is driving but gave the verbal :+1: in interest of time.

**Comment by michelleeeee** [comment]
@tsye15 @kirill2222 @wenders looks great to me too!

**Pull request merged**
